**AI AND APPLICATION (M504A AI AND APPLICATION(SS0625))**

NAME- SRAMANA BHATTACHARYA (GH1037191)

**EXPLORATORY DATA ANALYSIS OF A SUPERMARKET SALES AND PROFITS IN UNITED STATES**

**Business Context-**
 My client is a supermarketowner of United States.The owner has some outlets in different region of United States. The owner has provided me a dataset of his supermarket outlets. In this dataset the sales, profit, region, product category and product sub category informations are present. The owner need the data scientist to analyse the sales and profit for the month, category, sub categry from the dataset of his supermarket.

**Data Source-**
* The dataset is from the public source kaggle.com and the link to data source is https://www.kaggle.com/datasets/naveenkumar20bps1137/sample-superstore

* The dataset is a clean data set. I put NaN values here.

**Business Questions-**
1. What is the monthly sales of the store and identify which month had the highest sales and which month had the lowest sales?
2. Which category has the lowest sales and which category has the highest sales?
3. How are the sub categorical sales?
4. What is the monthly profit performance trend?
5. What is the profitby category and sub category?
6. Which region has highest profit and lowest profit?
7. What are the sales and profit by customer segment?
8. What ate the sales to profit ratio?

**How this notebook is organized based on assessment criteria?**
* As required by the assessment criteria, I will put the each respective business questions before the designed code-box during the execution of my notebook and discuss the code.
* During my code business questions are addressed by its serial number and the respective answer is addressed by "Ans-(serial no of questions)".
* I have generated some line graph, bar graph, pie chart to analysis the data which is necessary to get proper result.
* I have added the conclusion as a final discussion.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.colors as colors
pio.templates.default = "plotly_white"

In [ ]:
data = pd.read_csv("/content/My_data_with_NaN_csv", encoding = 'latin')
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1.0,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2.0,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3.0,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Corporate,United States,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4.0,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5.0,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990.0,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Consumer,United States,Miami,Florida,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3.0,0.20,4.1028
9990,9991.0,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2.0,0.00,15.6332
9991,9992.0,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Consumer,United States,Costa Mesa,NaN,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2.0,0.20,19.3932
9992,9993.0,CA-2017-121258,2/26/2017,03-03-2017,Standard Class,DB-13060,Consumer,United States,Costa Mesa,California,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4.0,0.00,13.3200
9993,9994.0,CA-2017-119914,05-04-2017,05-09-2017,Second Class,CC-12220,Consumer,United States,Westminster,California,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2.0,0.00,72.9480

**The dataset is loaded and shows we have 9994 rows and 19 columns.**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Row ID        9941 non-null   float64
 1   Order ID      9934 non-null   object
 2   Order Date    9930 non-null   object
 3   Ship Date     9952 non-null   object
 4   Ship Mode     9941 non-null   object
 5   Customer ID   9953 non-null   object
 6   Segment       9940 non-null   object
 7   Country       9950 non-null   object
 8   City          9944 non-null   object
 9   State         9930 non-null   object
 10  Region        9944 non-null   object
 11  Product ID    9946 non-null   object
 12  Category      9931 non-null   object
 13  Sub-Category  9936 non-null   object
 14  Product Name  9935 non-null   object
 15  Sales         9939 non-null   float64
 16  Quantity      9951 non-null   float64
 17  Discount      9945 non-null   float64
 18  Profit        9947 non-null   float64
dtypes: float64(5), object(14)
memory usage: 1.4+ MB

In [ ]:
data.describe()

            Row ID         Sales     Quantity     Discount       Profit
count  9941.000000   9939.000000  9951.000000  9945.000000  9947.000000
mean   4997.550548    230.179996     3.793388     0.156349    28.596673
std    2884.666921    624.450296     2.226591     0.206654   234.678622
min       1.000000      0.444000     1.000000     0.000000 -6599.978000
25%    2501.000000     17.290000     2.000000     0.000000     1.729500
50%    4999.000000     54.528000     3.000000     0.200000     8.643600
75%    7494.000000    209.970000     5.000000     0.200000    29.364000
max    9994.000000  22638.480000    14.000000     0.800000  8399.976000

In [ ]:
data.isna().sum()

Row ID          53
Order ID        60
Order Date      64
Ship Date       42
Ship Mode       53
Customer ID     41
Segment         54
Country         44
City            50
State           64
Region          50
Product ID      48
Category        63
Sub-Category    58
Product Name    59
Sales           55
Quantity        43
Discount        49
Profit          47
dtype: int64

**We can see here we have some NaN values in our dataset. We need to solve this by using data preprocessing method.**

In [ ]:
numerical_cols = data.select_dtypes(include = np.number).columns
data[numerical_cols] = data[numerical_cols].fillna(data[numerical_cols].mean())

categorical_cols = data.select_dtypes(include = 'object').columns
for col in categorical_cols:
  mode_val = data[col].mode()[0] if not data[col].mode().empty else np.nan
  data[col] = data[col].fillna(mode_val)

print("Missing values after filling:")
display(data.isna().sum())

Missing values after filling:

Row ID          0
Order ID        0
Order Date      0
Ship Date       0
Ship Mode       0
Customer ID     0
Segment         0
Country         0
City            0
State           0
Region          0
Product ID      0
Category        0
Sub-Category    0
Product Name    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

**We have cleared the NaN values with some techniques. For numerical columns, missing (NaN) values are placed with the mean of each respective. This ensures that the missing values don't distort the dataset, while keeping the distribution relatively stable. For each categorical column the mode is computed. If mode exist, missing values are filled with this most frequent category. If no mode exists, the code assign NaN. After filling missing values in both numerical and categorical columns, the code checks how many are left. This helps confirm whether the imputation was successful.**

In [ ]:
data.duplicated().values.any()

np.False_

**We don't have duplicate values. So we can start our exploratory data analysis now.**

In [ ]:
data['Order Date'] =pd.to_datetime(data['Order Date'], format = 'mixed')
data['Ship Date'] = pd.to_datetime(data['Ship Date'], format = 'mixed')

**Order Date and Ship Date, this two columns are being transformed into proper datetime object.**

In [ ]:
data['Order Year'] = data['Order Date'].dt.year
data['Order Month'] = data['Order Date'].dt.month
data['Order Day of Week'] = data['Order Date'].dt.dayofweek

**Extract the Year, Month and Day of Week from the Order Date. Three new columns are created (Order Year, Order Month, Order Day of Week) to store this value.**

In [ ]:
data.shape

(9994, 22)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Row ID             9994 non-null   float64
 1   Order ID           9994 non-null   object
 2   Order Date         9994 non-null   datetime64[ns]
 3   Ship Date          9994 non-null   datetime64[ns]
 4   Ship Mode          9994 non-null   object
 5   Customer ID        9994 non-null   object
 6   Segment            9994 non-null   object
 7   Country            9994 non-null   object
 8   City               9994 non-null   object
 9   State              9994 non-null   object
 10  Region             9994 non-null   object
 11  Product ID         9994 non-null   object
 12  Category           9994 non-null   object
 13  Sub-Category       9994 non-null   object
 14  Product Name       9994 non-null   object
 15  Sales              9994 non-null   float64
 16  Quantity           9994 non-null   float64
 17  Discount           9994 non-null   float64
 18  Profit             9994 non-null   float64
 19  Order Year         9994 non-null   int32
 20  Order Month        9994 non-null   int32
 21  Order Day of Week  9994 non-null   int32
dtypes: datetime64[ns](2), float64(5), int32(3), object(12)
memory usage: 1.6+ MB

**1. What is the monthly sales of the store and identify which month had the highest sales and which month had the lowest sales?**

In [ ]:
monthly_sales_trends =  data.groupby('Order Month')['Sales'].sum().reset_index()

monthly_sales_trends

    Order Month          Sales
0             1   95002.299592
1             2   58987.665388
2             3  204158.994784
3             4  137504.168596
4             5  154925.287696
5             6  153396.009276
6             7  147516.370988
7             8  158243.440984
8             9  321659.954464
9            10  198430.050684
10           11  351658.511168
11           12  318936.126460

In [ ]:
fig = px.line(monthly_sales_trends,
              x = 'Order Month',
              y = 'Sales',
              title = 'Monthly Sales Analysis')
fig.show()

**Ans-1) Sales begin moderately, drop sharply in 2nd month, and then recover significantly in the 3rd. Month 4 through 8 are flat with minor fluctuations. Sales picked up strongly in the final quarter, hitting their highest levels of the year, especially in month 11 and 9. The pick come in month 11, while the lowest point was back in month 2. The graph clearly shows a seasonal pattern in sales, with a slump early in the year followed by steady growth leading up to the end of the year. Likely boosted by holiday or seasonal demand.**

**2) Which category has the lowest sales and which category has the highest sales?**

In [ ]:
sales_by_category = data.groupby('Category')['Sales'].sum().reset_index()

In [ ]:
sales_by_category

          Category          Sales
0        Furniture  735726.867648
1  Office Supplies  732852.445468
2       Technology  831839.566964

In [ ]:
fig = px.pie(sales_by_category,
             values = 'Sales',
             names = 'Category',
             hole = 0.2,
             color_discrete_sequence = px.colors.qualitative.Pastel)
fig.update_traces(textposition = 'inside', textinfo = 'percent+label')
fig.update_layout(title_text = 'Sales Analysis by Category', titlefont = dict(size = 18))
fig.show()

**Ans-2) Technology makes up the biggest portion of sales, while Office Supplies contribute the least. The chart highlight that Technology brings in the most revenue, with furniture not far behind, and Office Supplies trailing. Overall, through, the three categories each make up a fairly balanced share of total sales.**

**3) How were the sub categorical sales?**

In [ ]:
sales_by_subcategory = data.groupby('Sub-Category')['Sales'].sum().reset_index()

In [ ]:
sales_by_subcategory

   Sub-Category          Sales
0   Accessories  167026.821968
1    Appliances  107447.655000
2           Art   27550.559984
3       Binders  214749.612972
4     Bookcases  114209.472296
5        Chairs  325422.582988
6       Copiers  149528.030000
7     Envelopes   16423.890000
8     Fasteners    3448.199992
9   Furnishings   92018.199976
10       Labels   12776.837988
11     Machines  189118.631000
12        Paper   80687.561948
13       Phones  328065.819996
14      Storage  223442.293988
15     Supplies   46673.538000
16       Tables  201829.171984

In [ ]:
fig = px.bar(sales_by_subcategory,
             x = 'Sub-Category',
             y = 'Sales',
             title = 'Sales Analysis by Sub Category')
fig.show()

**Ans-3) The chairs and Phones Sub-Categories have the highest sales and the lowest Sales are for Fasteners. There's a big difference in sales between the top and bottom categories, which is key for a business to know what's selling and what's not.**

**4) What is the monthly profit performance trend?**

In [ ]:
profit_by_month = data.groupby('Order Month')['Profit'].sum().reset_index()

In [ ]:
profit_by_month

    Order Month        Profit
0             1   9046.698173
1             2   9848.498646
2             3  28756.356039
3             4  11525.375193
4             5  22348.195146
5             6  21297.737266
6             7  13691.297193
7             8  21636.704046
8             9  40097.918412
9            10  31893.576920
10           11  35423.363693
11           12  40229.430912

In [ ]:
fig = px.line(profit_by_month,
              x = 'Order Month',
              y = 'Profit',
              title = 'Monthly Profit Analysis')
fig.show()

**Ans-4) The highest profit was in months 12 and 9 also show a significant profit. The lowest profit was in month 1. Profit was also low month 2 and 4. The figure shows a general upward trend in profit, particularly in the letter half of the year. The profit in the first half of the year were relatively low, with the exception of month 3. The second half of the year shows consistently higher profit levels, with month 9, 11 and 12 being particularly strong. There is a sharp increase from month 2 to month 3, followed by a drop in month 4. Similarly profit dips in month 7 and month 10 before recovering.**

**5) What is the profit by category and subcategory?**

In [ ]:
profit_by_category = data.groupby('Category')['Profit'].sum().reset_index()

In [ ]:
profit_by_category

          Category         Profit
0        Furniture   18402.564566
1  Office Supplies  123054.084141
2       Technology  144338.502932

In [ ]:
fig = px.pie(profit_by_category,
             values = 'Profit',
             names = 'Category',
             hole = 0.2,
             color_discrete_sequence = px.colors.qualitative.Pastel)
fig.update_traces(textposition = 'inside', textinfo = 'percent+label')
fig.update_layout(title_text = 'Profit Analysis by Categoty', titlefont = dict(size = 18))
fig.show()

**Ans-5) The pie chart clearly illustrate that Technology and Office Supplies are primary drivers of profits, together making up the vast majority of the total. In stark contrast the Furniture category accounts for a very minor portion of the overall profit.**

In [ ]:
profit_by_subcategory = data.groupby('Sub-Category')['Profit'].sum().reset_index()

In [ ]:
profit_by_subcategory

   Sub-Category        Profit
0   Accessories  41255.096839
1    Appliances  17781.759473
2           Art   6611.972812
3       Binders  31104.364559
4     Bookcases  -3404.885600
5        Chairs  26592.759573
6       Copiers  55617.824900
7     Envelopes   6970.204973
8     Fasteners   1020.561320
9   Furnishings  13110.021020
10       Labels   5502.006300
11     Machines   3391.956900
12        Paper  33790.793185
13       Phones  44180.303666
14      Storage  21093.831446
15     Supplies  -1189.099500
16       Tables -17634.320227

In [ ]:
fig = px.bar(profit_by_subcategory,
             x = 'Sub-Category',
             y = 'Profit',
             title = 'Profit Analysis by Sub Category')
fig.show()

**Ans-5) The bar graph shows that while some subcategories like Copiers, Accessories and Phones are highly profitable, others such as Tables, Bookcases and Supplies are generating a loss. The data suggests a wide range of performance, with some subcategories being major profit drivers and others being a drain on overall profitability. The most extreme values are the high profit from Copies and the significant loss from Tables.**

**6) Which region has highest profit and lowest profit?**

In [ ]:
profit_by_region = data.groupby('Region')['Profit'].sum().reset_index()

In [ ]:
profit_by_region

    Region         Profit
0  Central   37171.379432
1     East   91367.655017
2    South   46469.564339
3     West  110786.552851

In [ ]:
fig = px.bar(profit_by_region,
             x = 'Region',
             y = 'Profit',
             title = 'Profit Analysis by Region')
fig.show()

**Ans-6) The West region generates the highest profit and the Central region records the lowest profit. Profits are strongest in the West and East region, while the Central and South region lag behind. This suggest higher profit opportunities in the Central and South regions.**

**7) What are the sales and profit by customer segment?**

In [ ]:
sales_profit_by_segment = data.groupby('Segment').agg({'Sales': 'sum', 'Profit': 'sum'}).reset_index()
color_palatte = colors.qualitative.Pastel

fig = go.Figure()
fig.add_trace(go.Bar(x = sales_profit_by_segment['Segment'],
                     y = sales_profit_by_segment['Sales'],
                     name = 'Sales',
                     marker_color = color_palatte[0]))

fig.add_trace(go.Bar(x = sales_profit_by_segment['Segment'],
                     y = sales_profit_by_segment['Profit'],
                     name = 'Profit',
                     marker_color = color_palatte[1]))

fig.update_layout(title = 'Sales and Profit Analysis by Customer Segment',
                  xaxis_title = 'Customer Segment', yaxis_title = 'Amount')
fig.show()

**Ans-7) Customer Segment has the hoghest sales. Also generates the highest profit, through profit is much smaller compared to sales. Corporate Segment has moderate sales. The profit is samller than consumers but still noticeble. Home office Segment has the lowest sales. Also shows the lowest profit among the three segments.**

**8) What are the sales to profit ratio?**

In [ ]:
sales_profit_by_segment = data.groupby('Segment').agg({'Sales': 'sum', 'Profit': 'sum'}).reset_index()
sales_profit_by_segment['Sales_to_Profit_Ratio'] = sales_profit_by_segment['Sales']  / sales_profit_by_segment['Profit']
print(sales_profit_by_segment[['Segment', 'Sales_to_Profit_Ratio']])

       Segment  Sales_to_Profit_Ratio
0     Consumer               8.639537
1    Corporate               7.735202
2  Home Office               7.181652

In [ ]:
fig = px.pie(sales_profit_by_segment,
             values = 'Sales_to_Profit_Ratio',
             names = 'Segment',
             hole = 0.2,
             color_discrete_sequence = px.colors.qualitative.Pastel)
fig.update_traces(textposition = 'inside', textinfo = 'percent+label')
fig.update_layout(title_text = 'Sales and Profit Ratio by Segment', title_font = dict(size = 18))
fig.show()

**Ans-8) We can see here, the consumer segment holds the leargest share of the sales and profit ratio at 36.7%. This indicates consumers contribute the most overall. The corporate segment accounts for 32.8%, making it the second-leargest contributor. The home office segment represents 30.5%,slightly lower than corporate. While smaller, it still holds a significant portion.**

**Conclusion-**
 * The dat was not cleaned.some missing values were there.
 * The sales were highest in month 11 and lowest in month 2.
 * Technology categories sales we high and OfficeSupply sales were less.
 * The Chaires and the Phones Sub Categories  have the highest sales, and the lowest sales are for Fasteners.
 * The highest Profit was in month 12 and lowest profit was in month 1.
 * Technology has the highest profit, and Furniturenhas the lowest profit.
 * In Sub Category the Copiers generates the highest profit and there is loss of profits in Tables.
 * The West region generates the highest profit, and the Central region records the lowest profit region.

** I had to use data.head(), data.info(), data.describe(), data.shape multiple times for better understanding. Due to word limit I removed this codes.**